#!/bin/sh

[ -z "$1" ] && echo "Need to specify the video file" && exit
[ -z "$2" ] && scale="0.25" || scale=$2
[ -z "$3" ] && sleeptime="0.25"||sleeptime=$3

./extractframes $1 >/dev/null 2>&1

video="${1%.*}"

tmp=$video.txt
>$tmp

for file in ${video}frames/*png;
do
	image2ascii -f $file -r $scale >> $tmp
	echo "" >> $tmp
done

awk "{print \$0;if(length(\$0) == 0){system(\"sleep $sleeptime\")} if(getline==0) exit(0);}" $tmp

echo $tmp
